import React from 'react';
import Starfield from '../../components/animations/Starfield';
import BlurReveal from '../../components/animations/BlurReveal';

export default function TermsAndConditions() {
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  return (
    <main className="flex-grow pt-32 pb-20 px-6 w-full relative z-10">
      {/* Background */}
      <div className="fixed inset-0 z-[-1] bg-[#050507]">
        <Starfield speed={0.5} color="#A78BFA" className="opacity-30" />
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(124,58,237,0.1),transparent_50%)] pointer-events-none" />
      </div>

      {/* Hero Section */}
      <section className="text-center mb-16 pt-10">
        <BlurReveal>
          <p className="text-xs font-semibold tracking-[0.2em] text-[#06B6D4] mb-4 uppercase">LEGAL</p>
          <h1 className="text-4xl md:text-5xl font-display font-medium mb-6 text-[#F8FAFC] tracking-tight">Terms & Conditions</h1>
          <p className="text-lg text-[#CBD5E1] max-w-2xl mx-auto mb-4 leading-relaxed">
            These terms govern your use of the XYNEX platform and services.
          </p>
          <p className="text-sm text-[#94A3B8]">Last Updated: {currentDate}</p>
        </BlurReveal>
      </section>

      {/* Legal Content */}
      <section className="max-w-[800px] mx-auto bg-[rgba(13,13,20,0.65)] backdrop-blur-xl border border-[#272333] rounded-[24px] p-8 md:p-16 shadow-[0_0_30px_rgba(124,58,237,0.05)] mb-10">
        <div className="prose prose-invert max-w-none prose-headings:font-display prose-headings:font-medium prose-h2:text-2xl prose-h2:text-[#F8FAFC] prose-h2:mb-4 prose-h2:mt-10 prose-p:text-[#CBD5E1] prose-p:leading-relaxed prose-li:text-[#CBD5E1] prose-a:text-[#A78BFA] hover:prose-a:text-[#22D3EE] transition-colors">
          
          <p className="text-[#94A3B8] italic mb-8">
            Note: These Terms & Conditions are provided as a draft for the XYNEX platform and should be reviewed by a qualified legal professional.
          </p>

          <h2 className="mt-0">1. Acceptance of Terms</h2>
          <p>
            By accessing or using the XYNEX platform, you agree to be bound by these Terms & Conditions and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using this site and our services.
          </p>

          <h2>2. Use of the Platform</h2>
          <p>
            XYNEX provides an intelligent digital universe for spatial design and exploration. You are granted a limited, non-exclusive, non-transferable license to use the platform for its intended purpose. You may not use the platform in any way that causes, or may cause, damage to the platform or impairment of the availability or accessibility of XYNEX.
          </p>

          <h2>3. User Accounts</h2>
          <p>
            To use certain features of the platform, you must register for an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to provide accurate, current, and complete information during the registration process.
          </p>

          <h2>4. User-Created Content</h2>
          <p>
            You are entirely responsible for the content, designs, and dimensions you create, upload, or shape using XYNEX. You must ensure you have the necessary rights to use any uploaded material. You agree not to upload any unlawful, infringing, or malicious content.
          </p>

          <h2>5. Design Services & Outputs</h2>
          <p>
            The designs, spaces, and dimensions generated by the XYNEX platform are for conceptual and exploratory purposes. Outputs may vary, and you should independently review and verify any designs before relying on them for physical construction or engineering purposes. XYNEX does not provide professional architectural or engineering guarantees.
          </p>

          <h2>6. Intellectual Property</h2>
          <p>
            The XYNEX brand, logo, website design, underlying software, and platform content (excluding user-created content) are the intellectual property of XYNEX and are protected by applicable copyright and trademark law. You may not copy, reproduce, or distribute our intellectual property without prior written consent.
          </p>

          <h2>7. Prohibited Activities</h2>
          <p>Users are strictly prohibited from:</p>
          <ul>
            <li>Engaging in illegal or unauthorized activities on the platform.</li>
            <li>Attempting to gain unauthorized access to our systems, databases, or other users' accounts.</li>
            <li>Using the platform to distribute malicious software or spam.</li>
            <li>Abusing the design generation tools or attempting to disrupt the service for others.</li>
            <li>Uploading content that infringes upon the intellectual property rights of others.</li>
          </ul>

          <h2>8. Third-Party Services</h2>
          <p>
            XYNEX may integrate with or link to third-party services. We are not responsible for the content, terms, or privacy practices of these third-party platforms. Your use of such services is subject to their respective terms.
          </p>

          <h2>9. Availability</h2>
          <p>
            While we strive to keep XYNEX running smoothly, we do not guarantee uninterrupted service. The platform may occasionally be unavailable due to maintenance, updates, or unforeseen technical issues.
          </p>

          <h2>10. Disclaimer</h2>
          <p>
            The materials and services on the XYNEX platform are provided on an 'as is' basis. XYNEX makes no warranties, expressed or implied, and hereby disclaims all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property.
          </p>

          <h2>11. Limitation of Liability</h2>
          <p>
            In no event shall XYNEX or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on the XYNEX platform, even if XYNEX has been notified orally or in writing of the possibility of such damage.
          </p>

          <h2>12. Changes to Terms</h2>
          <p>
            We may revise these Terms & Conditions at any time without prior notice. By using this platform you are agreeing to be bound by the then-current version of these Terms & Conditions. Significant changes will be communicated by updating the "Last Updated" date.
          </p>

          <h2>13. Governing Law</h2>
          <p>
            These terms and conditions are governed by and construed in accordance with the laws of [GOVERNING JURISDICTION TO BE CONFIRMED], and you irrevocably submit to the exclusive jurisdiction of the courts in that location.
          </p>

          <h2>14. Contact</h2>
          <p>
            If you have any questions regarding these Terms & Conditions, please contact us at:
            <br />
            <a href="mailto:dharaneesh0530@gmail.com">dharaneesh0530@gmail.com</a>
          </p>

        </div>
      </section>
    </main>
  );
}
